name: RELEASE

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node_version: [14.x]
        os:
          - windows-latest
        include:
          - os: windows-latest
            TARGET_PLATFORMS: win32

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Package Electron
        run: |
          npm install -g node-gyp
          export npm_config_node_gyp=%USERPROFILE%\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js
          npm i
          npm run rebuild-native
          npm run pack

      - uses: actions/upload-artifact@v3
        with:
          name: Release
          path: |
            LICENSE
            out/*.dmg
            out/*.exe
          if-no-files-found: error
