name: RELEASE

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  windows-build:
    runs-on: windows-latest

    strategy:
      matrix:
        node_version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Package Electron
        run: |
          npm i --ignore-scripts
          npm run rebuild-native
          npm run pack
        env:
          TARGET_PLATFORMS: win32
